    const weapons = [
      {
        owned: true,
        name: '9MM PISTOL',
        clip: 12,
        ammo: 12,
        reserve: 96,
        rate: 0.28,
        dmg: 28,
        speed: 780,
        spread: 0.018,
        load: 0.9,
      },
      {
        owned: false,
        name: 'MACHINE PISTOL',
        clip: 30,
        ammo: 30,
        reserve: 150,
        rate: 0.085,
        dmg: 17,
        speed: 850,
        spread: 0.085,
        load: 1.25,
      },
      {
        owned: false,
        name: 'PUMP SHOTGUN',
        clip: 6,
        ammo: 6,
        reserve: 36,
        rate: 0.7,
        dmg: 19,
        speed: 740,
        spread: 0.16,
        pellets: 6,
        load: 1.6,
      },
      {
        owned: false,
        name: 'BAZOOKA',
        clip: 1,
        ammo: 1,
        reserve: 8,
        rate: 0.8,
        dmg: 180,
        speed: 410,
        spread: 0,
        load: 1.8,
        rocket: true,
      },
      {
        owned: false,
        name: 'ASSAULT RIFLE',
        clip: 30,
        ammo: 30,
        reserve: 150,
        rate: 0.12,
        dmg: 33,
        speed: 1100,
        spread: 0.03,
        load: 1.5,
      },
      {
        owned: false,
        name: 'PRECISION RIFLE',
        clip: 5,
        ammo: 5,
        reserve: 30,
        rate: 1.1,
        dmg: 105,
        speed: 1500,
        spread: 0.003,
        load: 1.9,
      },
    ];
    const missions = [];
